import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import {
  MermaidGeneratedSharedModule,
  SchematicGrammarGeneratedModule as SchematicGeneratedModule,
} from '../generated/module.js';
import { SchematicTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `Schematic` services.
 */
interface SchematicAddedServices {
  parser: {
    TokenBuilder: SchematicTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `Schematic` services.
 */
export type SchematicServices = LangiumCoreServices & SchematicAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `Schematic` services.
 */
export const SchematicModule: Module<
  SchematicServices,
  PartialLangiumCoreServices & SchematicAddedServices
> = {
  parser: {
    TokenBuilder: () => new SchematicTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSchematicServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  Schematic: SchematicServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const Schematic: SchematicServices = inject(
    createDefaultCoreModule({ shared }),
    SchematicGeneratedModule,
    SchematicModule
  );
  shared.ServiceRegistry.register(Schematic);
  return { shared, Schematic };
}
